# Generated by Django 4.2 on 2023-07-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_department_student_id_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_id',
            old_name='student_id',
            new_name='student_ID',
        ),
    ]
