# Generated by Django 4.2 on 2023-07-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_id',
            old_name='student_ID',
            new_name='student_id',
        ),
    ]
