# Generated by Django 4.2 on 2023-07-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_rename_student_id_student_id_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Department',
            new_name='department',
        ),
    ]
