# Generated by Django 4.2 on 2023-07-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_subject_subject_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='subject_marks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject_marks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject_marks',
            name='subject',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subject_Marks',
        ),
    ]
